# .autopilot/flip-gates.ps1 — automate MVP-GATES.md scorecard flips
#
# Flips gate checkboxes in .autopilot/MVP-GATES.md based on evidence, then
# commits / pushes / creates PR / auto-merges. Idempotent: re-running with
# the same state is a no-op (no commit created when nothing changes).
#
# Usage:
#   .\.autopilot\flip-gates.ps1 `
#       -Flips "G1=x,G4=x,G6=x,G7=x,G5=~,G8=~" `
#       -Reason "Evidence refreshed via PR #20" `
#       -Evidence "mvp-gates-evidence.md" `
#       -PRs "17,18,19,20"
#
# States: x (complete) | ~ (partial) | ' ' (not started — use space-in-quotes)

[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)][string]$Flips,
    [Parameter(Mandatory=$true)][string]$Reason,
    [string]$Evidence = "mvp-gates-evidence.md",
    [string]$PRs = "",
    [switch]$NoPR = $false,   # skip PR/merge; leave commit on current branch
    [switch]$DryRun = $false
)

$ErrorActionPreference = "Stop"

# --- locate repo root ---
$repoRoot = (git rev-parse --show-toplevel 2>$null)
if (-not $repoRoot) { throw "Not inside a git repo." }
Set-Location $repoRoot
$gatesPath = Join-Path $repoRoot ".autopilot/MVP-GATES.md"
if (-not (Test-Path $gatesPath)) { throw "MVP-GATES.md not found at $gatesPath" }

# --- verify evidence file exists ---
if ($Evidence -and -not (Test-Path (Join-Path $repoRoot $Evidence))) {
    throw "Evidence file missing: $Evidence — abort flip."
}

# --- parse flips ---
$flipMap = @{}
foreach ($pair in $Flips -split ",") {
    $kv = $pair.Trim() -split "="
    if ($kv.Count -ne 2) { throw "Bad flip syntax: '$pair'. Expected 'G1=x'." }
    $gate = $kv[0].Trim().ToUpper()
    $state = $kv[1].Trim()
    if ($state -notmatch '^[x~ ]$') { throw "Bad state '$state' for $gate. Must be x, ~, or ' '." }
    $flipMap[$gate] = $state
}

# --- read, modify in-memory ---
$lines = Get-Content $gatesPath
$newLines = New-Object System.Collections.Generic.List[string]
$currentGate = $null
$changed = $false

foreach ($line in $lines) {
    # Detect gate header: "## G5 — ..."
    if ($line -match '^## (G\d+) —') {
        $currentGate = $Matches[1]
        $newLines.Add($line) | Out-Null
        continue
    }
    # First checkbox line after a gate header
    if ($currentGate -and $flipMap.ContainsKey($currentGate) -and $line -match '^- \[([x~ ])\] ') {
        $oldState = $Matches[1]
        $newState = $flipMap[$currentGate]
        if ($oldState -ne $newState) {
            $newLine = $line -replace '^- \[[x~ ]\] ', "- [$newState] "
            $newLines.Add($newLine) | Out-Null
            Write-Host "  $currentGate : [$oldState] -> [$newState]"
            $changed = $true
        } else {
            $newLines.Add($line) | Out-Null
        }
        $currentGate = $null  # only first checkbox counts
        continue
    }
    $newLines.Add($line) | Out-Null
}

if (-not $changed) {
    Write-Host "No state changes — scorecard already matches requested flips. Exiting cleanly."
    exit 0
}

# --- append flip history line ---
$date = Get-Date -Format "yyyy-MM-dd"
$flipsLabel = ($flipMap.GetEnumerator() | Sort-Object Name | ForEach-Object {
    "$($_.Key) -> [$($_.Value)]"
}) -join ", "
$prLabel = if ($PRs) { " Commits: PR #" + ($PRs -split "," -join ", PR #") + "." } else { "" }
$historyLine = "- $date — $flipsLabel. $Reason.$prLabel"
$newLines.Add($historyLine) | Out-Null

# --- write ---
if ($DryRun) {
    Write-Host "`n--- DRY RUN — diff preview ---"
    Write-Host "History line: $historyLine"
    Write-Host "(no file write, no git action)"
    exit 0
}

$newLines | Set-Content $gatesPath -Encoding UTF8
Write-Host "Wrote: $gatesPath"

# --- git ---
$flipSlug = ($flipMap.Keys | Sort-Object) -join "-"
$branch = "autopilot/flip-gates-$flipSlug-$(Get-Date -Format 'yyyyMMddHHmm')"
$commitMsg = "docs(mvp-gates): flip $flipsLabel

$Reason"

Write-Host "`ngit: branching $branch"
git checkout -b $branch | Out-Null
git add .autopilot/MVP-GATES.md | Out-Null
git commit -m $commitMsg | Out-Null
Write-Host "committed."

if ($NoPR) {
    Write-Host "-NoPR set — leaving commit on branch $branch. Skip push/PR/merge."
    exit 0
}

git push -u origin $branch | Out-Null
Write-Host "pushed."

$prBody = @"
## Summary
- Auto-flip MVP-GATES scorecard: $flipsLabel
- Reason: $Reason
- Evidence: [$Evidence]($Evidence)$(if($PRs){"`n- Cited PRs: #" + ($PRs -split "," -join ", #")}else{""})

🤖 Generated by .autopilot/flip-gates.ps1
"@
$prTitle = "docs(mvp-gates): auto-flip scorecard"
gh pr create --title $prTitle --body $prBody | Out-Null
Write-Host "PR created."
gh pr merge --squash --delete-branch | Out-Null
Write-Host "merged + branch deleted."
git checkout main | Out-Null
git pull --ff-only | Out-Null
Write-Host "`nDone."
